#!/usr/bin/env bash

#shellcheck source=../../../.qfuncs.sh
source ~/.qfuncs.sh

set -e

# dereference in case of symlink
real_path="$(realpath "$0")"
real_dir="$(dirname "$real_path")"
cd "$real_dir" || die
"$real_dir"/bin/activate
/Applications/FontForge.app/Contents/MacOS/FFPython "$real_dir"/gen-font-variants.py "$@"
