#!/usr/bin/env bash

#shellcheck source=../../../.qfuncs.sh
source ~/.qfuncs.sh

set -e

# dereference in case of symlink
real_path="$(realpath "$0")"
real_dir="$(dirname "$real_path")"
cd "$real_dir" || die
. bin/activate
gen-font-variants.py "$@"
